THREAD_TYPES = [
    "TCP Null Flood",
    "SYN Flood",
    "ACK Flood",
    "RST Flood",
    "SYN-ACK Flood",
    "Christmas Tree Packet Attack(FPU)",
    "Christmas Tree Packet Attack(0X40)",
    "Christmas Tree Packet Attack(0X40)",
    "UDP Flood",
    "ICMP Flood",
    "HTTP GET Flood",
    "HTTP POST Flood",
    "Slowloris",
    "DNS amplification",
]
